const MODULE = `codeSample/users/`;
const actionTypes = {
  FETCH_REQUEST: `${MODULE}FETCH_REQUEST`,
  FETCH_FAIL: `${MODULE}FETCH_FAIL`,
  FETCH_SUCCESS: `${MODULE}FETCH_SUCCESS`,
  SELECT_USER: `${MODULE}SELECT_USER`,
  CLEAR_SELECTED_USER: `${MODULE}CLEAR_SELECTED_USER`,
  CLEAR_USER_LIST: `${MODULE}CLEAR_USER_LIST`,
  RESET: `${MODULE}RESET`
};

export default actionTypes;
